### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by hqulxw123** [yanbai1993/Embedding-Network#1]
This error occurs when I run document of .sh
![error](https://user-images.githubusercontent.com/44118301/55683374-935c7f80-5971-11e9-8207-d789e58ae1f3.jpg)

**Comment by hqulxw123** [comment]
> This error occurs when I run document of .sh
> ![error](https://user-images.githubusercontent.com/44118301/55683374-935c7f80-5971-11e9-8207-d789e58ae1f3.jpg)

**Comment by hqulxw123** [comment]
How should I solve this problem? I sincerely hope to get your answer.

**Comment by yanbai1993** [comment]
Here is an assert to ensure max_class=len(classes -1). Please check your data set list. If the dataset size is 13164 in vehicleID dataset, then your vehicle ids/classes need to be numbered from 0 to 13163.

**Comment by hqulxw123** [comment]
> Here is an assert to ensure max_class=len(classes -1). Please check your data set list. If the dataset size is 13164 in vehicleID dataset, then your vehicle ids/classes need to be numbered from 0 to 13163.

Thank you very much for your reply, I successfully solved this problem! ! !

**Comment by hqulxw123** [comment]
I have already trained and validated on the VehicleID dataset, so how do I train on the Reri dataset.

**Comment by chenchenver** [comment]
你好，我想问下您是怎么修改的数据集呢，我修改后用记事本和写字板打开分别是这样的，可以运行，但训练出的模型评价超级差，MAP大概是0.05，想知道你是怎么解决的呢~~谢谢！！
![QQ图片20190611170947](https://user-images.githubusercontent.com/44572100/59259314-22389180-8c6c-11e9-85b6-bee0242889ba.png)
![QQ图片20190611171125](https://user-images.githubusercontent.com/44572100/59259324-28c70900-8c6c-11e9-947a-1322b6f99b39.png)
