### ISSUE TITLE
Image-to-track evaluation for VeRi?

### ISSUE THREAD

**Issue by jonbakerfish** [yanbai1993/Embedding-Network#2]
Hi @yanbai1993 , thanks for open-sourcing your work. I check the [evaluation](https://github.com/yanbai1993/Embedding-Network/blob/master/veri_evaluate/baseline_evaluation_FACT_776.m) of VeRi-776, but it seems that the reid process is `image-to-image` instead of `image-to-track`. Am I missing something here?

**Comment by yanbai1993** [comment]
I think, we just use the retrieval pipeline to solve the ReID task, both in Vehicle ReID field and person ReID field. We extract the features of queries and all images in the database, then calculate their distance. The images calculation is one by one. Besides, we do not use the location information or camera ids information. 

For VeRI-776 dataset, the ground truth is saved in the following form:
query1 gt1 gt2 gt3 gt4.....
query2 gt1 gt2 gt3 gt4.....
.....

The evaluation code is : 
 for i = 1:nTest
    dist_line = fgetl(fidin);
    dist_line = str2num(dist_line);
    dist_SIFT(i, 1:length(dist_line)) = dist_line; 

For every query, we calculate the distances of  all  images.

This evaluation code is modified based on the result format we generated.  Compared to the evaluation code provided by the veri-776 author (https://github.com/VehicleReId/VeRidataset.), we just modify several codes.

**Comment by jonbakerfish** [comment]
OK, thanks for the clarification. The [official matlab code](https://github.com/VehicleReId/VeRidataset) evaluates the model in a `image-to-image` fashion, where the gallery size equals to the number of test images. For `image-to-track`, the gallery size is 2021 according to the ECCV'16 paper and I think the track information is required for this evaluation.
