### ISSUE TITLE
the evaluation for Veri dataset

### ISSUE THREAD

**Issue by hqulxw123** [yanbai1993/Embedding-Network#3]
thanks for open-sourcing your work. 
When I tested on the veri database, I found that the result was a bit high, MAP was as high as 72, I don't know if I missed something.
My steps are like this，Did I have a problem with the label?
When training veri, I gave a label similar to vehicleid to its txt.
#######.jip 0
#######.jip 1   
When testing veri, I used embed_##.sh to generate query.model and test.model
Then send it to veri_dist.py to generate dist_50000.txt
Then use the matlab code you provided to test the map
Did I miss something？ the test results could not reach the similar range provided by your article

**Comment by yanbai1993** [comment]
your result is right. Based on my code, the resnet50 backbone can achieve ~73 mAP performance.

发自我的 iPhone

在 2019年6月10日，11:24，hqulxw123 <notifications@github.com<mailto:notifications@github.com>> 写道：


thanks for open-sourcing your work.
When I tested on the veri database, I found that the result was a bit high, MAP was as high as 72, I don't know if I missed something.
My steps are like this，Did I have a problem with the label?
When training veri, I gave a label similar to vehicleid to its txt.
#######.jip 0
#######.jip 1
When testing veri, I used embed_##.sh to generate query.model and test.model
Then send it to veri_dist.py to generate dist_50000.txt
Then use the matlab code you provided to test the map
Did I miss something？ the test results could not reach the similar range provided by your article
